/* The Eureka Marketing Co. — interactivity
   - Fixed nav scroll state
   - Mobile menu toggle
   - Smooth scroll for in-page anchors (with nav offset)
   - IntersectionObserver scroll reveals
   - Subtle hero parallax
   No content is generated by JS. */

(function () {
  'use strict';

  var nav = document.querySelector('.site-nav');
  var toggle = document.querySelector('.nav-toggle');
  var links = document.querySelector('.nav-links');

  // Nav scrolled state
  function onScrollNav() {
    if (!nav) return;
    if (window.scrollY > 12) nav.classList.add('scrolled');
    else nav.classList.remove('scrolled');
  }
  window.addEventListener('scroll', onScrollNav, { passive: true });
  onScrollNav();

  // Mobile menu
  if (toggle && links) {
    toggle.addEventListener('click', function () {
      var open = links.classList.toggle('open');
      toggle.classList.toggle('open', open);
      toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
    });

    links.querySelectorAll('a').forEach(function (a) {
      a.addEventListener('click', function () {
        links.classList.remove('open');
        toggle.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
      });
    });
  }

  // Smooth scroll with fixed-nav offset
  function navOffset() {
    var h = document.querySelector('.site-nav');
    return h ? h.offsetHeight : 0;
  }
  document.querySelectorAll('a[href^="#"]').forEach(function (a) {
    a.addEventListener('click', function (e) {
      var id = a.getAttribute('href');
      if (id.length < 2) return;
      var target = document.querySelector(id);
      if (!target) return;
      e.preventDefault();
      var top = target.getBoundingClientRect().top + window.scrollY - navOffset() + 1;
      window.scrollTo({ top: top, behavior: 'smooth' });
      if (history.replaceState) history.replaceState(null, '', id);
    });
  });

  // Scroll reveals
  var revealEls = document.querySelectorAll('.reveal');
  if ('IntersectionObserver' in window && revealEls.length) {
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) {
          en.target.classList.add('in');
          io.unobserve(en.target);
        }
      });
    }, { threshold: 0.12, rootMargin: '0px 0px -8% 0px' });
    revealEls.forEach(function (el) { io.observe(el); });
  } else {
    revealEls.forEach(function (el) { el.classList.add('in'); });
  }

  // Hero parallax (subtle)
  var heroBg = document.querySelector('.hero-bg');
  if (heroBg && window.matchMedia('(pointer: fine)').matches &&
      !window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    var ticking = false;
    window.addEventListener('scroll', function () {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(function () {
        var y = window.scrollY;
        if (y < window.innerHeight) {
          heroBg.style.transform = 'translate3d(0,' + (y * 0.18) + 'px,0)';
        }
        ticking = false;
      });
    }, { passive: true });
  }
  // Photo placeholders: each page-scoped key owns exactly one stored image.
  var placeholderImageStorageKey = 'temc.placeholderImages.v1';
  var placeholderImages = {};
  try {
    placeholderImages = JSON.parse(localStorage.getItem(placeholderImageStorageKey) || '{}');
  } catch (_) {
    placeholderImages = {};
  }

  function setPlaceholderImage(placeholder, source) {
    var image = placeholder.querySelector('img');
    if (!image) {
      image = document.createElement('img');
      image.alt = placeholder.getAttribute('data-label') || 'Selected image';
      placeholder.appendChild(image);
    }
    image.src = source;
  }

  document.querySelectorAll('.ph[data-image-key]').forEach(function (placeholder) {
    var imageKey = placeholder.getAttribute('data-image-key');
    if (placeholderImages[imageKey]) setPlaceholderImage(placeholder, placeholderImages[imageKey]);

    placeholder.tabIndex = 0;
    placeholder.setAttribute('role', 'button');
    placeholder.setAttribute('title', 'Select an image for this placeholder');

    function selectImage() {
      var input = document.createElement('input');
      input.type = 'file';
      input.accept = 'image/*';
      input.addEventListener('change', function () {
        var file = input.files && input.files[0];
        if (!file) return;
        var reader = new FileReader();
        reader.addEventListener('load', function () {
          placeholderImages[imageKey] = reader.result;
          try {
            localStorage.setItem(placeholderImageStorageKey, JSON.stringify(placeholderImages));
          } catch (_) {
            delete placeholderImages[imageKey];
            return;
          }
          setPlaceholderImage(placeholder, reader.result);
        });
        reader.readAsDataURL(file);
      });
      input.click();
    }

    placeholder.addEventListener('click', selectImage);
    placeholder.addEventListener('keydown', function (event) {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        selectImage();
      }
    });
  });

})();
